services:
  multiplication:
    build: .
    container_name: multiplication-app
    networks:
      - default
    restart: unless-stopped
    ports:
      - 1987:80
      
networks:
  default:
    external: true
    name: web
