version: '3.8'

services:
  web:
    build: .
    container_name: maths-app
    ports:
      - "1987:80"
    volumes:
      - static_content:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  static_content:

networks:
  nginx-proxy:
    external: true 