services:
  multiplication:
    build: .
    container_name: multiplication-app
    networks:
      - default
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.proxy_host=multiplication"
    restart: unless-stopped
    ports:
      - 6666:6666
      
networks:
  default:
    external: true
    name: web
