services:
  web:
    build: 
      context: https://github.com/ludovicmorisset/mathematiques.git
    image: ludovicmorisset/mathematiques:latest
    ports:
      - "1987:80"
    volumes:
      - static_content:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - default
    
volumes:
  static_content:

networks:
  default:
    external: true
    name: web