version: '3.8'

services:
  web:
    build: .
    container_name: multiplication-app
    networks:
      - nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.proxy_host=multiplication"
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true 