services:
  web:
    build: .
    container_name: maths-app
    ports:
      - "1987:80"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: web
